### PR TITLE
fix feature flaws

### LINKED ISSUE #113: [PE-D] findpets command
Not sure if it's meant to be like that but I have 2 pets:
1. Baby Pao
2. Babypao

findpets Baby only gives me Baby Pao, but not Babypao

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dargohzy/ped#2

### PR DESCRIPTION
**Pull request by tianqi77**
enable findcommand to find pets with part of the names matching key words

### CODE REVIEW

File: src/main/java/clzzz/helper/commons/util/StringUtil.java [hunk 1]
```diff
@@ -35,7 +35,14 @@ public static boolean containsWordIgnoreCase(String sentence, String word) {
         String[] wordsInPreppedSentence = preppedSentence.split("\\s+");
 
         return Arrays.stream(wordsInPreppedSentence)
-                .anyMatch(preppedWord::equalsIgnoreCase);
+                .anyMatch(eachWord -> containsAsSubstringIgnoreCase(eachWord, preppedWord));
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/commons/util/StringUtil.java]: Wouldn't containsIgnoreCase() be enough?

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/StringUtil.java]: 🤔

Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/StringUtil.java]: ok haha I didn't know there is such function
