### PR TITLE
Fix functionality bug

### LINKED ISSUE #117: [PE-D] Index error messge
'deleteslot -1' and 'deleteslot 10000' should give the same error message

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hans555/ped#3

### LINKED ISSUE #121: [PE-D] bug in error display message
wrong error message shown.
format of date is correct but still unable to add

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: garysyndromes/ped#6

### LINKED ISSUE #130: [PE-D] Does not catch error for invalid 30 Feb Date
When invalid date 30/02 is entered, no invalid date error is thrown back to user. Instead date is rounded off to end of the month to 28/02. This could cause scheduling errors if a user is unaware of the non-existent date and does not re-verify the date of birth of the pet added.

Invalid dates for the month of february should be caught and indicated to the user as invalid dates and the pet should not automatically be added with another DOB.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: akhilvuputuri/ped#2

### PR DESCRIPTION
**Pull request by tianqi77**
bugs with dates i.e. invalid dates, or possibly too early/late dates

### CODE REVIEW

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java [hunk 1]
```diff
@@ -21,4 +22,71 @@
...
+            return day <= 30;
+        default:
+            return true;
+        }
+    }
+
+    /**
+     * Check if the given yrat is a leap year.
+     */
+    public static boolean isLeap(int year) {
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: LocalDate#isLeapYear()

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java [hunk 2]
```diff
@@ -21,4 +22,71 @@
...
+            }
+            return false;
+        case 4:
+        case 6:
+        case 9:
+        case 11:
+            return day <= 30;
+        default:
+            return true;
+        }
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: LocalDate#lengthOfMonth()

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java [hunk 3]
```diff
@@ -10,7 +11,7 @@
     // datetime-related
     public static final String DATETIME_PATTERN = "d/M/yyyy HHmm";
     public static final DateTimeFormatter DATETIME_FORMAT =
-            DateTimeFormatter.ofPattern(DATETIME_PATTERN);
+            DateTimeFormatter.ofPattern(DATETIME_PATTERN).withResolverStyle(ResolverStyle.LENIENT);
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: Why not set this to strict and then check day against length of month?
LENIENT doesn't make sense to me since it simply means #130 will be accepted rather than rounded inward.
STRICT checks outer range so it won't reject 29 to 31, if I'm not misinterpreting the documentation.

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: https://howtodoinjava.com/java/date-time/resolverstyle-strict-date-parsing/
Actually just setting it to STRICT does all the checking for you 🤔

**Review by shenghaoc — COMMENTED** [review]
You should expect the wheel to have been invented for you

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java [hunk 4]
```diff
@@ -21,4 +22,71 @@
...
+        int year = Integer.parseInt(parsedDate[2]);
+        return isValidDate(day, month, year);
+    }
+
+    /**
+     * Check if the given time is a valid time.
+     */
+    public static boolean isValidTimeString(String time) {
+        int timeInt = Integer.parseInt(time);
+        if (timeInt < 0 || timeInt >= 2400) {
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: I just checked, STRICT works for time also.
And it rejects 24 cos that'd be 0.

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: Oops you're rejecting 24 also, sorry it's late and I'm tired 😓

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 3 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: because if I set to strict i will not allow input like "12/03/2020" since it does not match "d/m/yyyy". That's why I need to put linient first and the check if the date is valid by myself.

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 4 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: same reason as above

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 2 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: thx! I go change it

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 3 above)
Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: dd/MM/yyyy?

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: This would mean we can't use the same format for output if we don't want the padding, but I don't think either the number of different formats or the presence of the padding would be an issue.

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 4 above)
Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: Should’ve expected that a math major would know how to handle 24, unlike me until I ran the code.
But similar to the above we can also relax the format

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: 😬

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 2 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: I can't use isLeapYear() or lengthOfMonth() cuz that needs me to convert the string to Localdate first. But if I want to keep the padding, I need to stick to LINIENT/SMART resolverstyle, and that will possibly change the year/month in the adapted localdate. That will affect the result of the functions u mentioned. I think it is better to just manually check it.

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 3 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: Another reason why I dont use STRICT is that both invalid date and invalid format will throw the same exception when parsing the string to localdate. Anyways I need to differentiate between them again and throw different error messages. Don't think it will be more convenient to use STRICT...

File: src/main/java/clzzz/helper/logic/parser/pet/AddPetCommandParser.java [hunk 5]
```diff
@@ -79,6 +80,11 @@ public AddPetCommand parse(String args) throws ParseException {
         if (argMultimap.getAllValues(PREFIX_DOB).size() > 1) {
             warningMessage += Messages.WARNING_MESSAGE_DOB;
         }
+        if (dateOfBirth.value.isBefore(LocalDate.EPOCH)) {
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/logic/parser/pet/AddPetCommandParser.java:83]: I think I can have a pet turtle born before 1970? Actually how do we define a hard lower bound for this?

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 2 above)
Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: If we follow ab3, we’d always have a wrapper class and check with a regex.
But now for some attributes we either just use library classes or don’t use regex for validation.
I find it strange that on the one hand we choose to use the library classes for convenience, on the other hand we insist on rewriting a parser for them.

Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: just use STRICT? I believe dd accepts both 1 and 01

Comment (tianqi77) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java]: no I checked alr, it doesn't...

File: src/main/java/clzzz/helper/commons/util/DateTimeUtil.java (hunk 3 above)
Comment (shenghaoc) [reply src/main/java/clzzz/helper/commons/util/DateTimeUtil.java:15]: Can’t argue with that

File: src/main/java/clzzz/helper/logic/parser/pet/AddPetCommandParser.java (hunk 5 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/logic/parser/pet/AddPetCommandParser.java:83]: that's why it is a warning not a exception. I set at 1970 cuz I feel it is suitable for most pets

File: src/main/java/clzzz/helper/logic/parser/ParserUtil.java [hunk 6]
```diff
@@ -94,6 +96,9 @@ public static DateOfBirth parseDateOfBirth(String dateOfBirth) throws ParseExcep
         if (!DateOfBirth.isValidDateOfBirth(trimmedDateOfBirth)) {
             throw new ParseException(DateOfBirth.MESSAGE_CONSTRAINTS);
         }
+        if (!DateTimeUtil.isValidDateString(trimmedDateOfBirth)) {
+            throw new ParseException(Messages.MESSAGE_INVALID_DATE);
+        }
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/logic/parser/ParserUtil.java]: The naming doesn't make any sense, a valid date of birth is of course of a valid date. The sole purpose of having two checks is to have separate error messages.
Consider AB3's [Email](https://github.com/nus-cs2103-AY1920S2/addressbook-level3/blob/master/src/main/java/seedu/address/model/person/Email.java), which lists out possible errors without identifying them. 
Consider also our [Food](https://github.com/AY1920S2-CS2103-W15-4/main/blob/master/src/main/java/clzzz/helper/model/pet/Food.java), which checks both food name and amount but does not misleadingly call either check isValidFood().

Comment (shenghaoc) [reply src/main/java/clzzz/helper/logic/parser/ParserUtil.java]: isValidDateOfBirth already uses LocalDate.parse with LENIENT to check the format, and then the date ranges are checked manually.
This is our own wrapper class, calling library class functions is inherently wasteful, the result of calling parse is ignored, so why not just call parse again with STRICT?

File: src/main/java/clzzz/helper/logic/parser/slot/SlotParserUtil.java [hunk 7]
```diff
@@ -79,6 +80,15 @@ public static LocalDateTime parseDateTime(String dateTime) throws ParseException
...
         }
+        if (!DateTimeUtil.isValidDateString(trimmedDateTime.split("\\s+")[0])) {
+            if (!DateTimeUtil.isValidTimeString(trimmedDateTime.split("\\s+")[1])) {
+                throw new ParseException(Messages.MESSAGE_INVALID_DATE_TIME);
+            }
+            throw new ParseException(Messages.MESSAGE_INVALID_DATE);
+        }
+        if (!DateTimeUtil.isValidTimeString(trimmedDateTime.split("\\s+")[1])) {
+            throw new ParseException(Messages.MESSAGE_INVALID_TIME);
+        }
```
Comment (shenghaoc) [inline src/main/java/clzzz/helper/logic/parser/slot/SlotParserUtil.java]: This is a library class, so let's not be stingy.
LocalDate.parse() -> you can check invalid date
LocalTime.parse() -> you can check invalid time
LocalDateTime.of(LocalDate date, LocalTime time)

File: src/main/java/clzzz/helper/logic/parser/ParserUtil.java (hunk 6 above)
Comment (tianqi77) [reply src/main/java/clzzz/helper/logic/parser/ParserUtil.java]: ok then I will try that

Comment (tianqi77) [reply src/main/java/clzzz/helper/logic/parser/ParserUtil.java]: emm actually it doesn't work. cuz even if the date is in correct format and is valid, like 1/1/2020, strict will always throw an exception. if u really want to do that, we have to make user input follow dd/mm/yyyy strictly.

Comment (shenghaoc) [reply src/main/java/clzzz/helper/logic/parser/ParserUtil.java]: uuuu
😭😭
